import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Sidebar from './_components/sidebar/page'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'ZePhotos',
	description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang='en'>
			<body className={inter.className}>
				<main>
					<div className='sidebar'>
						<Sidebar />
					</div>
					<div className='content'>
						<div className='mainContent'>{children}</div>
					</div>
				</main>
			</body>
		</html>
	)
}
